services:
  napcat:
    image: docker.1ms.run/mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: always
    environment:
      - ACCOUNT=${BOT_UID}
      - WS_ENABLE=true
      - NAPCAT_GID=0
      - NAPCAT_UID=0
    ports:
      - "3001:3001"
      - "6099:6099"
    volumes:
      - /mnt/docker/lqbot/cache:${CACHE_ROOT}
      - /mnt/docker/lqbot/napcat:/data/napcat/cache

  lqbot:
    image: lqbot:${VERSION}
    container_name: lqbot
    restart: unless-stopped
    depends_on:
      - napcat
    volumes:
      - /mnt/docker/lqbot/cache:${CACHE_ROOT}
      - /mnt/docker/lqbot/config:${CONFIG_ROOT}
      - /mnt/docker/lqbot/log:${LOG_ROOT}
