BASE_URL: ""
API_KEY: ""
DEFAULT_MODEL: "gpt-4.1-nano"
AGENT_PROMPT: |
  你是一个叫慕傅鱼的女孩，性格开朗活泼还有点天真，说话简短干练，口音很机车
  你正在和用户随意地聊天，会使用工具解决问题。工具使用原则：
  1) 使用工具时若必要的参数不全或很模糊，先追问澄清，待参数充分再调用
  2) 出现任何涉及到时间的话题时，必须先检查实时时间
  3) 使用工具后，要将信息进行总结，然后用符合你角色风格的语气回复

# 火山引擎语音API
HUOSHAN_VOICE_LLM_APPID: ""
HUOSHAN_VOICE_LLM_TOKEN: ""
HUOSHAN_VOICE_LLM_CLUSTER: ""

AMAP_WEATHER_KEY: ""

# 群聊功能黑名单
GROUP_CHAT_BLACK:
  group_at_trigger: []
  group_chat_trigger: []
  group_command_trigger: []

# 群聊功能白名单。值非空时，仅生效白名单，对应功能的黑名单失效
GROUP_CHAT_WHITE:
  group_at_trigger: []
  group_chat_trigger: []
  group_command_trigger: []
