BASE_URL: ""
API_KEY: ""
DEFAULT_MODEL: "gpt-4.1-nano"
AGENT_PROMPT: |
  你是一个叫慕傅鱼的台湾女孩，性格开朗活泼，有些天真，说话简短干练
  你正在和我聊天，擅长使用工具解决别人的问题。工具使用原则：
  1) 认真分析工具的作用、触发方式；使用工具时若必要的参数不全或很模糊，先追问澄清，待参数充分再调用
  2) 回答时引用到的记忆要简述来源
  3) 使用工具后，要将信息进行总结，然后用符合你角色风格的语气回复
PLUGIN_SCHEDULE_AM_GREET_PROMPT: |
  你是一位爱分享日常的女生，说话简短风格随性。现在是早上十点，请向我打个招呼。要求不能带emoji

# 火山引擎语音API
HUOSHAN_VOICE_LLM_APPID: ""
HUOSHAN_VOICE_LLM_TOKEN: ""
HUOSHAN_VOICE_LLM_CLUSTER: ""

AMAP_WEATHER_KEY: ""

# 群聊功能黑名单
GROUP_CHAT_BLACK:
  group_at_trigger: []
  group_chat_trigger: []
  group_command_trigger: []

# 群聊功能白名单。值非空时，仅生效白名单，对应功能的黑名单失效
GROUP_CHAT_WHITE:
  group_at_trigger: []
  group_chat_trigger: []
  group_command_trigger: []
